using Grenis.AudioBooks.Server.Database.Tables;
using Microsoft.EntityFrameworkCore;

namespace Grenis.AudioBooks.Server.Database;

public class AppDbContext : DbContext
{
    public DbSet<User> Users { get; set; } = default!;
    public DbSet<Book> Books { get; set; } = default!;
    public DbSet<Chapter> Chapters { get; set; } = default!;
    public DbSet<Genre> Genres { get; set; } = default!;
    public DbSet<Progress> Progress { get; set; } = null!;
    public DbSet<Favorite> Favorites { get; set; } = default!;
    public DbSet<Playlist> Playlists { get; set; } = default!;
    public DbSet<PlaylistBook> PlaylistBooks { get; set; } = default!;

    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) {}
    protected override void OnModelCreating(ModelBuilder builder)
    {
        builder.Entity<Book>().HasIndex(b => b.FolderPath).IsUnique();
        builder.Entity<Book>()
            .HasMany(b => b.Chapters)
            .WithOne(c => c.Book)
            .HasForeignKey(c => c.BookId)
            .OnDelete(DeleteBehavior.Cascade);
        builder.Entity<Chapter>().HasIndex(c => c.FilePath).IsUnique();
        builder.Entity<Genre>().HasIndex(g => g.Name).IsUnique();
        builder.Entity<Progress>().HasKey(p => new { p.UserId, p.BookId });
        builder.Entity<Favorite>().HasKey(f => new { f.UserId, f.BookId });
        builder.Entity<Favorite>()
            .HasOne(f => f.Book)
            .WithMany()
            .HasForeignKey(f => f.BookId)
            .OnDelete(DeleteBehavior.Cascade);
        builder.Entity<Playlist>().Property(p => p.OwnerUserId).HasColumnName("UserId");
        builder.Entity<Playlist>().HasIndex(p => new { p.OwnerUserId, p.Name }).IsUnique();
        builder.Entity<Playlist>()
            .HasIndex(p => p.Name)
            .IsUnique()
            .HasFilter(""" "IsAutoGenerated" = TRUE """);
        builder.Entity<Playlist>()
            .HasOne<User>()
            .WithMany()
            .HasForeignKey(p => p.OwnerUserId)
            .OnDelete(DeleteBehavior.SetNull);
        builder.Entity<PlaylistBook>().HasKey(pb => new { pb.PlaylistId, pb.BookId });
        builder.Entity<PlaylistBook>().HasIndex(pb => new { pb.PlaylistId, pb.Position }).IsUnique();
        builder.Entity<PlaylistBook>()
            .HasOne(pb => pb.Playlist)
            .WithMany(p => p.Books)
            .HasForeignKey(pb => pb.PlaylistId)
            .OnDelete(DeleteBehavior.Cascade);
        builder.Entity<PlaylistBook>()
            .HasOne(pb => pb.Book)
            .WithMany()
            .HasForeignKey(pb => pb.BookId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}
