namespace Grenis.AudioBooks.Server.Database.Tables;

public class Playlist
{
    public int Id { get; set; }
    public int? OwnerUserId { get; set; }
    public string Name { get; set; } = string.Empty;
    public bool IsAutoGenerated { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }
    public List<PlaylistBook> Books { get; set; } = new();
}
