package se.grenangen.audex.data.model

import kotlinx.serialization.Serializable

@Serializable
data class PlaylistDto(
    val id: Int,
    val name: String,
    val isAutoGenerated: Boolean = false,
    val ownerUserId: Int? = null,
    val ownerEmail: String? = null,
    val canEdit: Boolean = false,
    val createdAt: String,
    val updatedAt: String,
    val books: List<BookDto> = emptyList()
)
