using Grenis.AudioBooks.Server.Database;
using Grenis.AudioBooks.Server.Database.Tables;
using Microsoft.EntityFrameworkCore;

namespace Grenis.AudioBooks.Server;

public class SeriesPlaylistSynchronizer
{
    private readonly AppDbContext _db;
    private readonly ILogger<SeriesPlaylistSynchronizer> _logger;

    public SeriesPlaylistSynchronizer(AppDbContext db, ILogger<SeriesPlaylistSynchronizer> logger)
    {
        _db = db;
        _logger = logger;
    }

    public async Task SyncAsync(CancellationToken ct = default)
    {
        var books = await _db.Books.AsNoTracking()
            .Select(book => new { book.Id, book.FolderPath, book.Title, book.CustomTitle })
            .ToListAsync(ct)
            .ConfigureAwait(false);

        var series = SeriesMatcher.GroupBooks(books.Select(book =>
            (book.Id, book.FolderPath, book.Title, book.CustomTitle)));

        var playlists = await _db.Playlists
            .Include(playlist => playlist.Books)
            .Where(playlist => playlist.IsAutoGenerated)
            .ToListAsync(ct)
            .ConfigureAwait(false);

        var seriesNames = series.Select(group => group.Name).ToHashSet(StringComparer.OrdinalIgnoreCase);
        var now = DateTime.UtcNow;
        var changed = false;

        foreach (var group in series)
        {
            var playlist = playlists.FirstOrDefault(p =>
                string.Equals(p.Name, group.Name, StringComparison.OrdinalIgnoreCase));

            if (playlist is null)
            {
                playlist = new Playlist
                {
                    OwnerUserId = null,
                    Name = group.Name,
                    IsAutoGenerated = true,
                    CreatedAt = now,
                    UpdatedAt = now
                };
                _db.Playlists.Add(playlist);
                playlists.Add(playlist);
                changed = true;
                _logger.LogInformation(
                    "Created shared series playlist '{Name}' with {Count} book(s).",
                    group.Name, group.Books.Count);
            }
            else if (playlist.OwnerUserId is not null)
            {
                playlist.OwnerUserId = null;
                changed = true;
            }

            if (await ReplaceMembershipAsync(playlist, group.Books, ct).ConfigureAwait(false))
            {
                playlist.UpdatedAt = now;
                changed = true;
            }
        }

        foreach (var stale in playlists.Where(playlist => !seriesNames.Contains(playlist.Name)).ToList())
        {
            _db.Playlists.Remove(stale);
            playlists.Remove(stale);
            changed = true;
            _logger.LogInformation("Removed stale series playlist '{Name}'.", stale.Name);
        }

        if (changed)
            await _db.SaveChangesAsync(ct).ConfigureAwait(false);
    }

    private async Task<bool> ReplaceMembershipAsync(Playlist playlist, IReadOnlyList<SeriesMembership> books, CancellationToken ct)
    {
        var desired = books.Select((book, position) => (book.BookId, Position: position)).ToList();
        var current = playlist.Books
            .OrderBy(entry => entry.Position)
            .Select(entry => (entry.BookId, entry.Position))
            .ToList();

        if (current.SequenceEqual(desired))
            return false;

        if (playlist.Books.Count > 0)
        {
            _db.PlaylistBooks.RemoveRange(playlist.Books);
            playlist.Books.Clear();
            if (playlist.Id != 0)
                await _db.SaveChangesAsync(ct).ConfigureAwait(false);
        }

        playlist.Books = books.Select((book, position) => new PlaylistBook
        {
            Playlist = playlist,
            BookId = book.BookId,
            Position = position
        }).ToList();

        return true;
    }
}
