namespace Grenis.AudioBooks.Core;

public class PlaylistDto
{
    public int Id { get; init; }
    public string Name { get; init; } = string.Empty;
    public bool IsAutoGenerated { get; init; }
    public int? OwnerUserId { get; init; }
    public string? OwnerEmail { get; init; }
    public bool CanEdit { get; init; }
    public DateTime CreatedAt { get; init; }
    public DateTime UpdatedAt { get; init; }
    public List<BookDto> Books { get; init; } = new();
}
