using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Grenis.AudioBooks.Server.Migrations
{
    /// <inheritdoc />
    public partial class AutoGeneratedPlaylists : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "IsAutoGenerated",
                table: "Playlists",
                type: "boolean",
                nullable: false,
                defaultValue: false);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "IsAutoGenerated",
                table: "Playlists");
        }
    }
}
